package com.xost.generator.constant;

public enum Status {
    SUCCESS,
    INVALID_PROPERTIES,
    FILE_NOT_FOUND,
    INVALID_FILE_STRUCTURE,
    INVALID_LINE_STRUCTURE,
    INVALID_CLASS_NAME_FORMAT,
    INVALID_VARIABLE_NAME_FORMAT,
    INVALID_START_INDEX_FORMAT,
    INVALID_END_INDEX_FORMAT,
    FILE_ALREADY_EXISTS;
}
